In [5]:
#행렬 합 구하기
matrix_1 = [
    [1,2],
    [3,4]
]

matrix_2 = [
    [5,6],
    [7,8]
]
result=[
    [0,0],
    [0,0]
]


In [6]:
row =0
column = 0
matrix_1[row][column]

1

In [7]:
for row in range(2):
    for column in range(2):
        result[row][column] = matrix_1[row][column] + matrix_2[row][column]

In [11]:
matrix_result =[]
for row in range(2):
    temp =[]
    for column in range(2):
        temp.append(matrix_1[row][column]+ matrix_2[row][column])
    print(temp)
    matrix_result.append(temp)
print(matrix_result)

[6, 8]
[10, 12]
[[6, 8], [10, 12]]


In [8]:
result

[[6, 8], [10, 12]]

In [13]:
#각 요소에 1씩 더하기
matrix_1 

for row in range(2):
    for column in range(2):
        matrix_1[row][column] += 1
print(matrix_1)

[[2, 3], [4, 5]]


In [5]:
#행렬 합 구하기 with numpy
import numpy as np

matrix_1 = [
    [1,2],
    [3,4]
]

matrix_2 = [
    [5,6],
    [7,8]
]

In [7]:
matrix_1 + matrix_2 #concat(연결)이 됨

[[1, 2], [3, 4], [5, 6], [7, 8]]

In [8]:
matrix_result = np.array(matrix_1) + np.array(matrix_2)
matrix_result

array([[ 6,  8],
       [10, 12]])

In [9]:
#모든 요소에 1 더하기
matrix_1 + 1 #안됨


TypeError: can only concatenate list (not "int") to list

In [10]:
np.array(matrix_1) +1

array([[2, 3],
       [4, 5]])

In [11]:
x=np.uint(40)
print(x.dtype)

uint32


In [12]:
print(type(x))

<class 'numpy.uint32'>


In [13]:
x = np.array([1,2,3,4])
print(x.dtype)

int32


In [14]:
x = np.float32([1,2,3,4])
print(x.dtype)

float32


In [15]:
x

array([1., 2., 3., 4.], dtype=float32)

In [17]:
x = np.array([1,2,3,4],dtype=np.float32)
print(x.dtype)
x

float32


array([1., 2., 3., 4.], dtype=float32)

In [20]:
y=np.int32(x)
print(y.dtype)
y

int32


array([1, 2, 3, 4])

In [21]:
x = np.array(1)
print(x.shape) #0차원 ()
print(x.ndim) #차원의 크기
print(x.size) #개수

()
0
1


In [22]:
x = np.array([1,2]) 
print(x.shape) #(2,)
print(x.ndim) #1
print(x.size) #2

(2,)
1
2


In [29]:
x = np.array([[1,2,3],[1,2,3]]) 
print(x.shape)
print(x.ndim)
print(x.size)

(2, 3)
2
6


In [33]:
x =np.arange(10)
print(x.dtype)
x

int32


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
x  = np.arange(1,10,2)
print(x.dtype)
x

int32


array([1, 3, 5, 7, 9])

In [36]:
x = np.arange(1,10,0.5)
print(x.dtype)
x

float64


array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [37]:
x = np.arange(10,1,-0.5)
x

array([10. ,  9.5,  9. ,  8.5,  8. ,  7.5,  7. ,  6.5,  6. ,  5.5,  5. ,
        4.5,  4. ,  3.5,  3. ,  2.5,  2. ,  1.5])

In [40]:
np.linspace(1,20,5) #값을 균등하게 시작값, 끝값, 벡터크기

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

In [41]:
np.linspace(1,20,5,endpoint=False) #endpoint => 끝 값 포함 여부 옵션

array([ 1. ,  4.8,  8.6, 12.4, 16.2])

In [43]:
x = np.arange(9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [52]:
x = np.arange(24).reshape(2,3,4)
print(x)
print('\n')

x = np.array([[1, 2], [3, 4], [5, 6]])
print(x.reshape(2,3))
print('\n')

x= np.arange(9).reshape(3,-1)
print(x)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


[[1 2 3]
 [4 5 6]]


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [54]:
x =np.arange(20)
print(x)
print(x[1:3])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[1 2]


In [58]:
x = np.arange(20).reshape(4,5)
print(x)
x[0:3:2, 3:5] #x[:3,3:]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


array([[ 3,  4],
       [13, 14]])

In [59]:
x = np.arange(20).reshape(4,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [64]:
x[2][2]
print(x[2,2])

12


In [73]:
x[x>3]
x[x==1]
~(x ==1)

array([[ True, False,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [77]:
x[(x>3) & (x<8)]

array([4, 5, 6, 7])

In [81]:
print(np.random.rand(5,5))
print(np.random.randint(1,10)) #마지막 값 포함 안한다
print(np.random.randint(1,10,size=(5,3))) #size = shape


[[0.78136811 0.55125642 0.59751977 0.50146662 0.25868729]
 [0.56265381 0.80173854 0.83604821 0.95202807 0.8193817 ]
 [0.08083906 0.93385219 0.48748589 0.86239264 0.16165267]
 [0.69066831 0.77145343 0.18621273 0.3500608  0.00831882]
 [0.92032813 0.34778313 0.56725272 0.79463254 0.26666172]]
1
[[8 8 5]
 [6 8 5]
 [1 7 8]
 [1 2 2]
 [9 3 4]]


In [82]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [83]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [84]:
np.eye(3) #대각행렬

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
x = np.random.rand(3,3)
x

array([[0.41277761, 0.74469647, 0.74376722],
       [0.38904628, 0.32612852, 0.59401227],
       [0.12355893, 0.30407767, 0.71914074]])

In [89]:
x.ravel(order='C') #옆으로 펼쳐주는 것
x.ravel(order='F') #아래로 펼쳐

array([0.17423753, 0.3314357 , 0.84626406, 0.49924741, 0.40615938,
       0.51869413, 0.95705441, 0.87309358, 0.47355769])

In [7]:
x = np.arange(1,4).reshape(1,3)
y = np.arange(4,7).reshape(1,3)
print(np.concatenate([x,y], axis =1)) #옆으로 합쳐짐 (1,6)
np.concatenate([x,y], axis =0) #행 그대로 합쳐짐 (2,3)

[[1 2 3 4 5 6]]


array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
z = np.concatenate([x,y],axis=0)
np.split(z,2) #나누는 거

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 1 and the array at index 1 has size 3

In [4]:
x = np.array([10,20,30]).reshape(3,1)
x

array([[10],
       [20],
       [30]])

In [99]:
y = np.arange(1,4)

In [100]:
x+y

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [101]:
np.argmin(x) #최소값 위치
np.argmax(x) #최대값 위치

2

In [3]:
print(x)
np.where(x>1,x,-100) ## 조건, True일 경우, False일 경우

None


TypeError: '>' not supported between instances of 'NoneType' and 'int'

In [3]:
# #실습01
# 1) x.dot(y) #행렬곱
# 2) x.linspace #균일한 간격
# 3) size
from audioop import mul

#실습 1
x = [1,2,3,4,5,6,7,8,9]
y = [10,20,30,40,50,60,70,80,90]

x = np.array(x).reshape(3,3)
y = np.array(y).reshape(3,3)
sum = x+y
multiple = x.dot(y)
print(sum)
print(multiple)

[[11 22 33]
 [44 55 66]
 [77 88 99]]
[[ 300  360  420]
 [ 660  810  960]
 [1020 1260 1500]]


In [114]:
#실습2
x = np.linspace(1,20,30)
y =np.array(x)+10
print(x)
print(y)

[ 1.          1.65517241  2.31034483  2.96551724  3.62068966  4.27586207
  4.93103448  5.5862069   6.24137931  6.89655172  7.55172414  8.20689655
  8.86206897  9.51724138 10.17241379 10.82758621 11.48275862 12.13793103
 12.79310345 13.44827586 14.10344828 14.75862069 15.4137931  16.06896552
 16.72413793 17.37931034 18.03448276 18.68965517 19.34482759 20.        ]
[11.         11.65517241 12.31034483 12.96551724 13.62068966 14.27586207
 14.93103448 15.5862069  16.24137931 16.89655172 17.55172414 18.20689655
 18.86206897 19.51724138 20.17241379 20.82758621 21.48275862 22.13793103
 22.79310345 23.44827586 24.10344828 24.75862069 25.4137931  26.06896552
 26.72413793 27.37931034 28.03448276 28.68965517 29.34482759 30.        ]


In [32]:
#실습3
import numpy as np
x = np.random.randint(1,100,size=(2,10,10)) #size = shape
y = np.where(x>=50,1,2)

y[1:,5:,5:]

array([[[1, 1, 2, 1, 2],
        [2, 2, 1, 1, 1],
        [2, 1, 2, 1, 2],
        [2, 2, 1, 2, 1],
        [2, 1, 1, 1, 1]]])

In [27]:
y = np.where(x>=50,1,2)
y


array([[[1, 1, 2, 2, 2, 2, 1, 1, 1, 2],
        [2, 1, 2, 1, 1, 2, 1, 1, 1, 1],
        [1, 2, 1, 1, 1, 1, 2, 2, 1, 1],
        [2, 1, 1, 2, 1, 2, 2, 1, 1, 2],
        [1, 2, 2, 1, 2, 1, 2, 1, 2, 1],
        [2, 2, 2, 2, 1, 2, 2, 2, 1, 2],
        [2, 1, 2, 2, 1, 1, 1, 2, 2, 1],
        [1, 1, 1, 2, 1, 2, 2, 1, 2, 1],
        [2, 2, 1, 2, 2, 1, 1, 1, 1, 2],
        [2, 2, 1, 1, 2, 2, 1, 1, 2, 2]],

       [[2, 2, 2, 2, 2, 1, 1, 1, 2, 2],
        [2, 1, 2, 1, 1, 2, 2, 1, 1, 2],
        [1, 1, 2, 2, 1, 1, 2, 1, 1, 1],
        [1, 2, 1, 2, 1, 2, 1, 1, 1, 1],
        [1, 1, 1, 2, 2, 1, 2, 1, 2, 2],
        [2, 1, 1, 2, 2, 2, 2, 1, 2, 1],
        [1, 1, 1, 2, 2, 2, 2, 1, 1, 1],
        [1, 1, 2, 1, 1, 1, 2, 2, 2, 1],
        [1, 2, 2, 2, 1, 2, 2, 2, 1, 2],
        [1, 1, 2, 1, 2, 2, 2, 2, 1, 1]]])

In [12]:
import pandas as pd

x = [1,2,3,4,5]
pd.Series(x) #인덱스, 값

0    1
1    2
2    3
3    4
4    5
dtype: int64